apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vajbcha
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: vajbcha
    newName: rg.fr-par.scw.cloud/djnd/vajbcha
    newTag: '16d78c672ab9bf8d42333c8b5332ee619b8f5562'
  - name: vajbcha-nginx
    newName: rg.fr-par.scw.cloud/djnd/vajbcha-nginx
    newTag: '16d78c672ab9bf8d42333c8b5332ee619b8f5562'
