apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vajbcha
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: vajbcha
    newName: rg.fr-par.scw.cloud/djnd/vajbcha
    newTag: '4227f61cd1e3b5aa44ed88d457f512ea3823a297'
  - name: vajbcha-nginx
    newName: rg.fr-par.scw.cloud/djnd/vajbcha-nginx
    newTag: '4227f61cd1e3b5aa44ed88d457f512ea3823a297'
