apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vajbcha
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: vajbcha
    newName: rg.fr-par.scw.cloud/djnd/vajbcha
    newTag: '22568bdea8a9e1f3d21b924e3b8a1c424cd2f7d3'
  - name: vajbcha-nginx
    newName: rg.fr-par.scw.cloud/djnd/vajbcha-nginx
    newTag: '22568bdea8a9e1f3d21b924e3b8a1c424cd2f7d3'
