name: Check types
on:
  push:
    branches:
      - "main"
jobs:
  check_python_types:
    name: Check Python types
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          (cd ./vajbcha && pip install -r requirements.txt)

      - name: Check types with mypy
        run: |
          (cd ./vajbcha && mypy .)
